version01 page
mflorezr/FE-trainingproject pull request #1
Opened 2020-09-04 17:17 UTC by mflorezr

2020-09-04 21:49 UTC, jscaicedom commented on general.css
> +}
Maybe you could use the css file that you actually have in the et-line folder to not copy the same code here.

2020-09-04 22:01 UTC, jscaicedom commented on general.css
> +    border: 3px  #5dc5ab solid;
you could use variables to avoid repeat the color code and to easy remember

2020-09-04 22:03 UTC, jscaicedom commented on general.css
> +    color: #5dc5ab;
same of the variable

2020-09-04 22:22 UTC, jscaicedom commented on general.css
> +        background: url("images/hover-image.jpg") no-repeat;
this line is unnecessary because you already put this in line 835, you don't have to repeat it, just put what changes.

2020-09-04 22:23 UTC, jscaicedom commented on general.css
> +        background: url("images/hover-image.jpg") no-repeat;
same here

2020-09-04 22:25 UTC, jscaicedom reviewed
general suggestions

2020-09-07 20:13 UTC, hackeo1 requested changes
- remove the .DS_Store files from the repo
- check the spaces configuration in you IDE to add spaces before the { symbols and after the ,
- it is recommended an indentation of 2 spaces instead of 4
-  be consisten in the use of units, I recommend using rem / em for sizes, position, margins, paddings
- font size must be rem/em
- use css variables to handle repeated values that will change consistently (colors, font sizes)
- the code is difficult to read, check the extra spaces and indentation for it, specially the HTML

2020-09-07 20:13 UTC, hackeo1 commented on animation.js
> +    showSlides(slideIndex=6);
don't use assignations in the parameters

2020-09-07 20:13 UTC, hackeo1 commented on animation.js
> +if(($(testimonial).is(" :hidden"))){
add this code to a function with a name so you don't need to add the comment

2020-09-07 20:13 UTC, hackeo1 commented on animation.js
> +var controller = new ScrollMagic.Controller({ globalSceneOptions: { duration: "100%" } });
divide the code in named functions and call them so you don't have to add a comment like this

2020-09-07 20:13 UTC, hackeo1 commented on animation.js
> +    .addTo(controller);
this code can be don't in a loop using a constant list

2020-09-07 20:13 UTC, hackeo1 commented on animation.js
> +  showSlides(slideIndex = n);
don't use assignation in the parameters of a call

2020-09-07 20:13 UTC, hackeo1 commented on animation.js
> +function currentSlide(n) {
don't use single character variables

2020-09-07 20:13 UTC, hackeo1 commented on animation.js
> +  var i;
use let/const instead of var, don't use single character variables

2020-09-07 20:13 UTC, hackeo1 commented on animation.js
> +      slides[i].style.display = "none";
avoid the use of inline styles

2020-09-07 20:13 UTC, hackeo1 commented on animation.js
> +  var dots = document.getElementsByClassName("dot");
use single quotes in JS

2020-09-07 20:13 UTC, hackeo1 commented on animation.js
> +  if (n < 1) {slideIndex = slides.length}
separate in multiple lines

2020-09-07 20:13 UTC, hackeo1 commented on animation.js
> +  }
use a array function instead of a for loop

2020-09-07 20:13 UTC, hackeo1 commented on animation.js
> +  for (i = 0; i < dots.length; i++) {
don't reuse the same variable for multiple loops

2020-09-07 20:13 UTC, hackeo1 commented on animation.js
> +  slides[slideIndex-1].style.display = "flex";
avoid the use of inline styles

2020-09-07 20:13 UTC, hackeo1 commented on animation.js
> +    element.addEventListener("click", function(){
Avoid using event listeners when it is possible, when you add them make sure you have a strategy in place to remove it when the piece of code is not needed anymore

2020-09-07 20:13 UTC, hackeo1 commented on animation.js
> +    element.addEventListener("click", function(){
use arrow function on anonymous functions, unless you need 'this' context

2020-09-07 20:13 UTC, hackeo1 commented on animation.js
> +    element.addEventListener("click", function(){
use onclick html attribute instead

2020-09-07 20:13 UTC, hackeo1 commented on animation.js
> +
remove extra lines

2020-09-07 20:13 UTC, hackeo1 commented on animation.js
> +    if ($(nav).is(':visible')){
indentation is not clear

2020-09-07 20:13 UTC, hackeo1 commented on et-line-font/Read Me.txt
> +See the documentation for more info on how to use this package: http://icomoon.io/#docs/font-face
this file is not needed in your repo, upload only the required assets

2020-09-07 20:13 UTC, hackeo1 commented on et-line-font/lte-ie7.js
> +window.onload = function() {
remove this file unless it is required in your code

2020-09-07 20:13 UTC, hackeo1 commented on et-line-font/style.css
> +.icon-mobile, .icon-laptop, .icon-desktop, .icon-tablet, .icon-phone, .icon-document, .icon-documents, .icon-search, .icon-clipboard, .icon-newspaper, .icon-notebook, .icon-book-open, .icon-browser,
use css selector to avoid having to add every .icon-*

2020-09-07 20:13 UTC, hackeo1 commented on general.css
> +}
repeated style in et-line-font/style.css

2020-09-07 20:13 UTC, hackeo1 commented on general.css
> +    fill: white;
don't use fill stroke and stroke width (svg attributes) in css, it is not cross platform

2020-09-07 20:13 UTC, hackeo1 commented on general.css
> +.carrousel-images h1{
avoid using tags to style elements

2020-09-07 20:13 UTC, hackeo1 commented on general.css
> +    color: white;
use hex, try using variables

2020-09-07 20:13 UTC, hackeo1 commented on general.css
> +    color: white;
hex

2020-09-07 20:13 UTC, hackeo1 commented on general.css
> +    background: url('images/home-bg.jpg')no-repeat ;
space missing after )

2020-09-07 20:13 UTC, hackeo1 commented on general.css
> +    animation:fade1 10s infinite;
fade1 is not a good name for an animation, describe what the animation is doing, don't tag a number to it

2020-09-07 20:13 UTC, hackeo1 commented on general.css
> +    animation:fade2 10s infinite;
fade1 is not a good name for an animation, describe what the animation is doing, don't tag a number to it

2020-09-07 20:13 UTC, hackeo1 commented on general.css
> +    background-size: cover;
use the background shortcut

2020-09-07 20:13 UTC, hackeo1 commented on general.css
> +    z-index: 200;
use z-index from 0-10 having in mind that 10 is never gonna have anything on top of it

2020-09-07 20:13 UTC, hackeo1 commented on general.css
> +}
change the name for the animations so it's descriptive enough

2020-09-07 20:13 UTC, hackeo1 commented on general.css
> +    color: white;
color in hex, try using variables

2020-09-07 20:13 UTC, hackeo1 commented on general.css
> +    font-weight: bold;
font weight in number

2020-09-07 20:13 UTC, hackeo1 commented on general.css
> +    color: white;
hex, variables

2020-09-07 20:13 UTC, hackeo1 commented on general.css
> +    font-weight: bold;
use number instead

2020-09-07 20:13 UTC, hackeo1 commented on general.css
> +.contact__but{
many styles are duplicated from the other *__but use a , separated style instead

2020-09-07 20:13 UTC, hackeo1 commented on general.css
> +    opacity: 100;
opacity is a number between 0 and 1

2020-09-07 20:13 UTC, hackeo1 commented on general.css
> +    border: 3px  white solid;
check the shortcut for border

2020-09-07 20:13 UTC, hackeo1 commented on general.css
> +    border: 3px rgb(155, 103, 6) solid;
consistency is key, use hex for all colors

2020-09-07 20:13 UTC, hackeo1 commented on general.css
> +    font-size:25px;
font size in rem

2020-09-07 20:13 UTC, hackeo1 commented on general.css
> +    padding-bottom: 0px;
0 doesn't have a unit

2020-09-07 20:13 UTC, hackeo1 commented on general.css
> +.slideshow-container {
divide the css code in different files instead of using comments

2020-09-07 20:13 UTC, hackeo1 commented on general.css
> +textarea, input{
avoid using tags for styling

2020-09-07 20:13 UTC, hackeo1 commented on general.css
> +}
add this to a class

2020-09-07 20:13 UTC, hackeo1 commented on general.css
> +@media (min-width:36rem){
use pixels for media queries

2020-09-07 20:13 UTC, hackeo1 commented on general.css
> +        display: flex !important;
don't use important, use specificity instead

2020-09-07 20:13 UTC, hackeo1 commented on index.html
> +    <svg aria-hidden="true" style="position: absolute; width: 0; height: 0; overflow: hidden;" version="1.1"
move svgs to a different file/files

2020-09-07 20:13 UTC, hackeo1 commented on index.html
> +            <div class='slide2'>
double quotes in HTML

2020-09-07 20:13 UTC, hackeo1 commented on index.html
> +
to many extra lines with no consistency, remove them

2020-09-07 20:13 UTC, hackeo1 commented on index.html
> +                    voluptate neque, curabitur dolor libero sodales</p>
when there is a tag that has more than one line of content, move the closing tag to the same indentation as the opening one, and move the content to an extra line

2020-09-07 20:13 UTC, hackeo1 commented on index.html
> +            </ul>
fix indentation for tags inside ul

2020-09-07 20:13 UTC, hackeo1 commented on index.html
> +                        <div class="team-contact__icons">
recommend avoiding double underscore in class names unless you are following BEM (all the file follows the strict rules of BEM)

2020-09-07 20:13 UTC, hackeo1 commented on index.html
> +                            <h1>Ilustration</h1>
the whole page must have only one h1, the rest of the headers must be used to have a map of the page, they are not meant to be used to give styles to the content

2020-09-07 20:13 UTC, hackeo1 commented on index.html
> +                <div style="text-align:center">
no inline styles allowed

2020-09-07 20:13 UTC, hackeo1 commented on index.html
> +    <script src="animation.js"></script>
it is recommended to use a dependency manager to add or remove libraries

2020-09-10 14:18 UTC, hackeo1 requested changes

2020-09-10 14:18 UTC, hackeo1 commented on animation.js
> +  let i = 0;
don't use single character variables

2020-09-10 14:18 UTC, hackeo1 commented on animation.js
> +      .setClassToggle('#' + buttonLink[j].id, "active-link")
single quotes in JS

2020-09-10 14:18 UTC, hackeo1 commented on animation.js
> +      slide.classList.remove("active-slide");
single quotes in JS

2020-09-10 14:18 UTC, hackeo1 commented on animation.js
> +toggleButton.addEventListener("click", function () {
use onclick instead

2020-09-10 14:18 UTC, hackeo1 commented on general.css
> +@keyframes fadeFirstSlide {
this name doesn't describe what the animation does, it describes where it is applied

2020-09-10 14:18 UTC, hackeo1 commented on general.css
> +  border: 0.18rem solid #9b6706;
use variables for the colors

2020-09-10 14:18 UTC, hackeo1 commented on general.css
> +  border: 1px solid #f8f5f5;
check the consistency of the colors, use hex for all of them, use variables for the colors

2020-09-10 14:18 UTC, hackeo1 commented on index.html
> +            <p class="service-text-description">Lorem ipsum dolor sit amet, maecenas eget vestibulum justo
move content to the next line

2020-09-10 14:18 UTC, hackeo1 commented on svgxuse.js
> +/*global XDomainRequest, MutationObserver, window */
use a dependency manager to add the libraries

2020-09-10 21:03 UTC, hackeo1 commented on animation.js
> +var controller = new ScrollMagic.Controller({
use let or const instead

2020-09-10 21:24 UTC, hackeo1 approved these changes

2020-09-10 21:32 UTC, merged